name: Python CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Detect relevant changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            python:
              - 'backend/**/*.py'
              - 'backend/**/*.pyi'
              - 'backend/pyproject.toml'
              - 'backend/uv.lock'
              - 'backend/mypy.ini'
              - 'backend/ruff.toml'
              - 'backend/.ruff.toml'

  type-checking:
    needs: detect_changes
    if: github.event_name == 'workflow_dispatch' ||
      needs.detect_changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install Dependencies
        working-directory: backend
        run: uv sync --dev

      - name: Run Mypy
        working-directory: backend
        run: uv run mypy

  tests:
    needs: detect_changes
    if: github.event_name == 'workflow_dispatch' ||
      needs.detect_changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install Dependencies
        working-directory: backend
        run: uv sync --dev

      - name: Run Pytest
        working-directory: backend
        run: uv run pytest

  lints:
    needs: detect_changes
    if: github.event_name == 'workflow_dispatch' ||
      needs.detect_changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: "./backend"

  format:
    needs: detect_changes
    if: github.event_name == 'workflow_dispatch' ||
      needs.detect_changes.outputs.python == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Ruff Formatting Checks
        uses: astral-sh/ruff-action@v3
        with:
          src: "./backend"
          args: "format --check --diff"
